development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: AnswerCompanion_development
  pool: 5
  username: root
  password: excel407
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: AnswerCompanion_development
  pool: 5
  username: root
  password: excel407
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: AnswerCompanion_development
  pool: 5
  username: root
  password: excel407
  host: localhost
